displayName=Bronzeman Unleashed
author=Elertan
support=
description=Ironman without the chores. Flexible rule sets for solo and group play. Works with existing or fresh accounts.
tags=gamemode,trade,restrict,group,bronzeman
plugins=com.elertan.BUPlugin
